language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION='2.3.*'
    - php: 5.5
      env: SYMFONY_VERSION='2.4.*'
    - php: 5.5
      env: SYMFONY_VERSION='dev-master'
  allow_failure:
    - php: hhvm


before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer install

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
